services:
  blog-cli:
    profiles:
      - src/blog
    extends:
      file: src/blog/compose.yml
      service: cli
  master-password-cli:
    profiles:
      - src/tools/master-password
    extends:
      file: src/tools/master-password/compose.yml
      service: cli