name: auto deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - update blog
      - update master password
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  update:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deploy.yml
