name: update blog

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: ./.github/workflows/update-submodule.yml
    with:
      path: src/blog
      label: blog